<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ouroboros</groupId>
        <artifactId>ouroboros-data</artifactId>
        <version>2.0.0-rc.1-SNAPSHOT</version>
    </parent>

    <artifactId>ouroboros-data-test-support</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.ouroboros</groupId>
            <artifactId>ouroboros-data-builders</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ouroboros</groupId>
            <artifactId>ouroboros-data-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ouroboros</groupId>
            <artifactId>ouroboros-data-sql</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ouroboros</groupId>
            <artifactId>ouroboros-data-sql-migration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
