package com.ouroboros.data.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.lang.reflect.Proxy;
import java.sql.SQLException;
import java.sql.Types;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;

import javax.sql.DataSource;

import org.junit.jupiter.api.Test;

import com.ouroboros.data.adapter.SqlDataAdapter;
import com.ouroboros.data.dsl.Operators;
import com.ouroboros.data.dsl.Order;
import com.ouroboros.data.dsl.SExpression;
import com.ouroboros.data.dsl.statement.DeleteStatement;
import com.ouroboros.data.dsl.statement.InsertStatement;
import com.ouroboros.data.dsl.statement.QueryStatement;
import com.ouroboros.data.dsl.statement.UpdateStatement;
import com.ouroboros.data.model.DataModel;
import com.ouroboros.data.model.DataModelField;
import com.ouroboros.data.transpile.BaseTranspileContext;
import com.ouroboros.data.transpile.DefaultQueryTranspiler;
import com.ouroboros.data.transpile.FieldSource;
import com.ouroboros.data.transpile.TranspileContext;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.NumberPath;
import com.querydsl.core.types.dsl.StringPath;
import com.querydsl.sql.ColumnMetadata;
import com.querydsl.sql.RelationalPathBase;

class KingbaseQuerydslIntegrationTest {
  private static final String TABLE_NAME = "CodexKingbaseQuerydslSmoke";
  private static final SmokeTable TABLE = new SmokeTable();

  @Test
  void shouldExecuteHighLevelCrudWithGeneratedKeyPaginationAndQuotedIdentifiers() throws Exception {
    DataSource dataSource = KingbaseIntegrationEnvironment.requireDataSource();
    executeDdl(dataSource, "DROP TABLE IF EXISTS \"" + TABLE_NAME + "\"");
    executeDdl(dataSource, "CREATE TABLE \"" + TABLE_NAME + "\" ("
        + "\"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        + "\"DisplayName\" VARCHAR(128) NOT NULL, \"Score\" INTEGER NOT NULL)");

    try {
      var adapter = new SqlDataAdapter(dataSource, "kingbase");
      TranspileContext context = context();

      var insertValues = new LinkedHashMap<String, Object>();
      insertValues.put("DisplayName", "alpha");
      insertValues.put("Score", 10);
      String generatedKey = adapter.insert(InsertStatement.of(TABLE_NAME, insertValues), context).get();
      assertNotNull(generatedKey);
      assertFalse(generatedKey.isEmpty());

      var updateValues = new LinkedHashMap<String, Object>();
      updateValues.put("DisplayName", "beta");
      assertEquals(1L, adapter.update(
          UpdateStatement.of(TABLE_NAME, updateValues, equalTo("DisplayName", "alpha")), context).get());

      QueryStatement query = QueryStatement.builder()
          .select(SExpression.field("Id"), SExpression.field("DisplayName"), SExpression.field("Score"))
          .from(TABLE_NAME)
          .where(equalTo("DisplayName", "beta"))
          .order("Id", Order.ASC)
          .offset(0)
          .limit(1)
          .build();
      var queryMetadata = new DefaultQueryTranspiler().applyWithContext(query, context).get();
      var records = adapter.query(queryMetadata).get();
      assertEquals(1, records.size());
      assertEquals("beta", records.get(0).get("DisplayName"));

      assertEquals(1L, adapter.delete(
          DeleteStatement.of(TABLE_NAME, equalTo("DisplayName", "beta")), context).get());
    } finally {
      executeDdl(dataSource, "DROP TABLE IF EXISTS \"" + TABLE_NAME + "\"");
    }
  }

  private static SExpression<Boolean> equalTo(String field, Object value) {
    return SExpression.create(Operators.EQ, SExpression.field(field), SExpression.constant(value));
  }

  private static TranspileContext context() {
    FieldSource source = new FieldSource() {
      @Override
      public Optional<Path<?>> getField(String fieldName) {
        if ("Id".equals(fieldName)) {
          return Optional.of(TABLE.id);
        }
        if ("DisplayName".equals(fieldName)) {
          return Optional.of(TABLE.displayName);
        }
        if ("Score".equals(fieldName)) {
          return Optional.of(TABLE.score);
        }
        return Optional.empty();
      }

      @Override
      public List<Path<?>> getFields() {
        return Arrays.<Path<?>>asList(TABLE.id, TABLE.displayName, TABLE.score);
      }

      @Override
      public Path<?> getSelfPath() {
        return TABLE;
      }

      @Override
      public Optional<DataModel> getDataModel() {
        return Optional.of(primaryKeyModel());
      }
    };
    return new BaseTranspileContext(source, TABLE_NAME, new DefaultQueryTranspiler());
  }

  private static DataModel primaryKeyModel() {
    var id = (DataModelField) Proxy.newProxyInstance(
        KingbaseQuerydslIntegrationTest.class.getClassLoader(),
        new Class<?>[]{DataModelField.class},
        (proxy, method, args) -> "getRawName".equals(method.getName()) ? "Id" : null);
    return (DataModel) Proxy.newProxyInstance(
        KingbaseQuerydslIntegrationTest.class.getClassLoader(),
        new Class<?>[]{DataModel.class},
        (proxy, method, args) -> "getPrimaryKeys".equals(method.getName())
            ? Collections.singletonList(id)
            : null);
  }

  private static void executeDdl(DataSource dataSource, String sql) throws SQLException {
    try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
      statement.execute(sql);
    }
  }

  private static final class SmokeTable extends RelationalPathBase<Object> {
    private static final long serialVersionUID = 1L;
    private final NumberPath<Long> id = createNumber("Id", Long.class);
    private final StringPath displayName = createString("DisplayName");
    private final NumberPath<Integer> score = createNumber("Score", Integer.class);

    private SmokeTable() {
      super(Object.class, "smoke", "", TABLE_NAME);
      addMetadata(id, ColumnMetadata.named("Id").withIndex(1).ofType(Types.BIGINT).notNull());
      addMetadata(displayName, ColumnMetadata.named("DisplayName").withIndex(2).ofType(Types.VARCHAR).notNull());
      addMetadata(score, ColumnMetadata.named("Score").withIndex(3).ofType(Types.INTEGER).notNull());
    }
  }
}
