package com.ouroboros.data.migration;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.Proxy;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

import javax.sql.DataSource;

import org.junit.jupiter.api.Test;

import com.ouroboros.data.model.DataModel;
import com.ouroboros.data.model.DataModelField;
import com.ouroboros.data.model.MigrationStrategy;
import com.ouroboros.data.model.ValueType;
import com.ouroboros.data.model.valuetypes.LongValue;
import com.ouroboros.data.model.valuetypes.StringValue;

class KingbaseLiquibaseIntegrationTest {
  private static final String TABLE_NAME = "codex_kingbase_liquibase_smoke";
  private static final String METADATA_TABLE_NAME = "codex_kingbase_metadata_smoke";

  @Test
  void shouldPreviewMigrateAndBecomeIdempotent() throws Exception {
    DataSource dataSource = KingbaseIntegrationEnvironment.requireDataSource();
    executeDdl(dataSource, "DROP TABLE IF EXISTS " + TABLE_NAME);

    try (var connection = dataSource.getConnection()) {
      connection.setAutoCommit(false);
      var models = Collections.singletonList(model());
      var migration = new DatabaseMigration(connection, "", "KingbaseLiquibaseIntegrationTest");

      var preview = migration.getMigrationSqls(models);
      assertTrue(preview.isRight(), () -> preview.getLeft().getMessage());
      assertFalse(preview.get().isEmpty());
      assertTrue(preview.get().stream().allMatch(sql -> !sql.endsWith("\n")));

      var migrated = migration.migrate(models);
      assertTrue(migrated.isRight(), () -> migrated.getLeft().getMessage());

      var repeatedPreview = new DatabaseMigration(connection, "", "KingbaseLiquibaseIntegrationTest")
          .getMigrationSqls(models);
      assertTrue(repeatedPreview.isRight(), () -> repeatedPreview.getLeft().getMessage());
      assertTrue(repeatedPreview.get().isEmpty());
    } finally {
      executeDdl(dataSource, "DROP TABLE IF EXISTS " + TABLE_NAME);
    }
  }

  @Test
  void shouldScanExistingMetadataApplyAlterDdlAndBecomeIdempotent() throws Exception {
    DataSource dataSource = KingbaseIntegrationEnvironment.requireDataSource();
    executeDdl(dataSource, "DROP TABLE IF EXISTS " + METADATA_TABLE_NAME);
    executeDdl(dataSource, "CREATE TABLE " + METADATA_TABLE_NAME + " ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        + "code VARCHAR(32) NOT NULL, "
        + "legacy_required VARCHAR(16) NOT NULL)");

    try (var connection = dataSource.getConnection()) {
      connection.setAutoCommit(false);
      var modelHolder = new DataModel[1];
      var id = field(modelHolder, "id", new LongValue(), false, true, null);
      var code = field(modelHolder, "code", new StringValue(), false, false, 128);
      var displayName = field(modelHolder, "display_name", new StringValue(), true, false, 64);
      var models = Collections.singletonList(model(METADATA_TABLE_NAME, modelHolder,
          Arrays.asList(id, code, displayName), Collections.singletonList(id)));

      var preview = new DatabaseMigration(connection, "", "KingbaseLiquibaseIntegrationTest")
          .getMigrationSqls(models);
      assertTrue(preview.isRight(), () -> preview.getLeft().getMessage());
      assertTrue(preview.get().stream().anyMatch(sql -> containsSql(sql, "ALTER TABLE")));
      assertTrue(preview.get().stream().anyMatch(sql -> containsSql(sql, "DISPLAY_NAME")));

      var migrated = new DatabaseMigration(connection, "", "KingbaseLiquibaseIntegrationTest")
          .migrate(models);
      assertTrue(migrated.isRight(), () -> migrated.getLeft().getMessage());

      var columns = readColumns(dataSource, METADATA_TABLE_NAME);
      assertNotNull(columns.get("code"));
      assertTrue(columns.get("code").characterMaximumLength >= 128);
      assertNotNull(columns.get("display_name"));
      assertTrue(columns.get("display_name").nullable);
      assertNotNull(columns.get("legacy_required"));
      assertTrue(columns.get("legacy_required").nullable);

      var repeatedPreview = new DatabaseMigration(connection, "", "KingbaseLiquibaseIntegrationTest")
          .getMigrationSqls(models);
      assertTrue(repeatedPreview.isRight(), () -> repeatedPreview.getLeft().getMessage());
      assertTrue(repeatedPreview.get().isEmpty());
    } finally {
      executeDdl(dataSource, "DROP TABLE IF EXISTS " + METADATA_TABLE_NAME);
    }
  }

  private static boolean containsSql(String sql, String expected) {
    return sql.toUpperCase(Locale.ROOT).contains(expected);
  }

  private static DataModel model() {
    var modelHolder = new DataModel[1];
    var id = field(modelHolder, "id", new LongValue(), false, true, null);
    var name = field(modelHolder, "name", new StringValue(), true, false, 128);
    return model(TABLE_NAME, modelHolder, Arrays.asList(id, name), Collections.singletonList(id));
  }

  private static DataModel model(String tableName, DataModel[] modelHolder, List<DataModelField> fields,
                                 List<DataModelField> primaryKeys) {
    DataModel model = (DataModel) Proxy.newProxyInstance(
        KingbaseLiquibaseIntegrationTest.class.getClassLoader(),
        new Class[]{DataModel.class},
        (proxy, method, args) -> switch (method.getName()) {
          case "getVersion" -> "1";
          case "getNamespace" -> "smoke";
          case "getName", "getRawName" -> tableName;
          case "getFullName" -> "smoke." + tableName;
          case "getLabel" -> "Kingbase Liquibase smoke";
          case "getDescription" -> "Kingbase Liquibase compatibility smoke table";
          case "getMigrationStrategy" -> MigrationStrategy.AUTO;
          case "getExtraProps" -> Collections.emptyMap();
          case "getExtraProp" -> Optional.empty();
          case "getFields" -> fields;
          case "getField" -> fields.stream()
              .filter(field -> field.getName().equals(String.valueOf(args[0])))
              .findFirst();
          case "getPrimaryKeys" -> primaryKeys;
          default -> defaultValue(method.getReturnType());
        });
    modelHolder[0] = model;
    return model;
  }

  private static DataModelField field(DataModel[] modelHolder, String name, ValueType<?> valueType,
                                      boolean nullable, boolean autoIncrement, Integer size) {
    return (DataModelField) Proxy.newProxyInstance(
        KingbaseLiquibaseIntegrationTest.class.getClassLoader(),
        new Class[]{DataModelField.class},
        (proxy, method, args) -> switch (method.getName()) {
          case "getName", "getRawName", "getLabel" -> name;
          case "getDescription" -> "Smoke " + name;
          case "getType" -> valueType.getName();
          case "getValueType" -> valueType;
          case "getRules" -> Collections.emptyList();
          case "getSize" -> size;
          case "getIsNullable" -> nullable;
          case "getIsUnsigned", "getIsUnique" -> false;
          case "getIsAutoIncrement" -> autoIncrement;
          case "getExtraProps" -> Collections.emptyMap();
          case "getExtraProp" -> Optional.empty();
          case "getDataModel" -> modelHolder[0];
          default -> defaultValue(method.getReturnType());
        });
  }

  private static Object defaultValue(Class<?> returnType) {
    if (returnType == Boolean.TYPE) {
      return false;
    }
    if (returnType == Integer.TYPE) {
      return 0;
    }
    if (returnType == Long.TYPE) {
      return 0L;
    }
    return null;
  }

  private static void executeDdl(DataSource dataSource, String sql) throws SQLException {
    try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
      statement.execute(sql);
    }
  }

  private static Map<String, ColumnState> readColumns(DataSource dataSource, String tableName) throws SQLException {
    var columns = new HashMap<String, ColumnState>();
    String sql = "SELECT column_name, is_nullable, character_maximum_length "
        + "FROM information_schema.columns WHERE table_schema = 'public' AND table_name = ?";
    try (var connection = dataSource.getConnection(); var statement = connection.prepareStatement(sql)) {
      statement.setString(1, tableName);
      try (var rs = statement.executeQuery()) {
        while (rs.next()) {
          columns.put(rs.getString("column_name"), new ColumnState(
              "YES".equalsIgnoreCase(rs.getString("is_nullable")),
              rs.getInt("character_maximum_length")));
        }
      }
    }
    return columns;
  }

  private record ColumnState(boolean nullable, int characterMaximumLength) {
  }
}
