package com.ouroboros.data.adapter;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Optional;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DelegatingDataSource;

import com.ouroboros.data.dsl.statement.InsertStatement;
import com.ouroboros.data.model.DataModel;
import com.ouroboros.data.model.DataModelField;
import com.ouroboros.data.transpile.BaseTranspileContext;
import com.ouroboros.data.transpile.FieldSource;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.NumberPath;
import com.querydsl.core.types.dsl.StringPath;
import com.querydsl.sql.ColumnMetadata;
import com.querydsl.sql.RelationalPathBase;

class SqlDataAdapterGeneratedKeyMetadataTest {
  private static final String TABLE_NAME = "generated_key_metadata";
  private static final GeneratedKeyTable TABLE = new GeneratedKeyTable();
  private static final ModelBackedTable MODEL_BACKED_TABLE = new ModelBackedTable();
  private static final IncompleteMetadataTable INCOMPLETE_METADATA_TABLE = new IncompleteMetadataTable();

  @Test
  void shouldRequestGeneratedKeysByRelationPrimaryKeyColumnName() {
    var target = new JdbcDataSource();
    target.setURL("jdbc:h2:mem:generated_key_metadata;DB_CLOSE_DELAY=-1");
    target.setUser("sa");
    target.setPassword("");
    var dataSource = new GeneratedKeyColumnTrackingDataSource(target);
    new JdbcTemplate(dataSource).execute("CREATE TABLE \"" + TABLE_NAME
        + "\" (\"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"DisplayName\" VARCHAR(64))");

    var values = new LinkedHashMap<String, Object>();
    values.put("DisplayName", "alpha");
    var generatedKey = new SqlDataAdapter(dataSource, "H2")
        .insert(InsertStatement.of(TABLE_NAME, values), context())
        .get();

    assertNotNull(generatedKey);
    assertArrayEquals(new String[]{"Id"}, dataSource.getGeneratedKeyColumnNames());
  }

  @Test
  void shouldRequestGeneratedKeysByDataModelPrimaryKeyWhenRelationHasNoPrimaryKey() {
    var target = new JdbcDataSource();
    target.setURL("jdbc:h2:mem:generated_key_model_metadata;DB_CLOSE_DELAY=-1");
    target.setUser("sa");
    target.setPassword("");
    var dataSource = new GeneratedKeyColumnTrackingDataSource(target);
    new JdbcTemplate(dataSource).execute("CREATE TABLE \"" + TABLE_NAME
        + "\" (\"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"DisplayName\" VARCHAR(64))");

    var values = new LinkedHashMap<String, Object>();
    values.put("DisplayName", "beta");
    var generatedKey = new SqlDataAdapter(dataSource, "H2")
        .insert(InsertStatement.of(TABLE_NAME, values), modelBackedContext())
        .get();

    assertNotNull(generatedKey);
    assertArrayEquals(new String[]{"Id"}, dataSource.getGeneratedKeyColumnNames());
  }

  @Test
  void shouldUseGenericGeneratedKeyRequestWhenPrimaryKeyColumnMetadataIsIncomplete() {
    var target = new JdbcDataSource();
    target.setURL("jdbc:h2:mem:generated_key_incomplete_metadata;DB_CLOSE_DELAY=-1");
    target.setUser("sa");
    target.setPassword("");
    var dataSource = new GeneratedKeyColumnTrackingDataSource(target);
    new JdbcTemplate(dataSource).execute("CREATE TABLE \"" + TABLE_NAME
        + "\" (\"Id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"DisplayName\" VARCHAR(64))");

    var values = new LinkedHashMap<String, Object>();
    values.put("DisplayName", "gamma");
    var generatedKey = new SqlDataAdapter(dataSource, "H2")
        .insert(InsertStatement.of(TABLE_NAME, values), incompleteMetadataContext())
        .get();

    assertNotNull(generatedKey);
    assertNull(dataSource.getGeneratedKeyColumnNames());
  }

  private static BaseTranspileContext context() {
    FieldSource source = new FieldSource() {
      @Override
      public Optional<Path<?>> getField(String fieldName) {
        if ("Id".equals(fieldName)) {
          return Optional.of(TABLE.id);
        }
        if ("DisplayName".equals(fieldName)) {
          return Optional.of(TABLE.displayName);
        }
        return Optional.empty();
      }

      @Override
      public List<Path<?>> getFields() {
        return Arrays.<Path<?>>asList(TABLE.id, TABLE.displayName);
      }

      @Override
      public Path<?> getSelfPath() {
        return TABLE;
      }

      @Override
      public Optional<DataModel> getDataModel() {
        return Optional.empty();
      }
    };
    return new BaseTranspileContext(source, TABLE_NAME);
  }

  private static BaseTranspileContext modelBackedContext() {
    FieldSource source = new FieldSource() {
      @Override
      public Optional<Path<?>> getField(String fieldName) {
        if ("Id".equals(fieldName)) {
          return Optional.of(MODEL_BACKED_TABLE.id);
        }
        if ("DisplayName".equals(fieldName)) {
          return Optional.of(MODEL_BACKED_TABLE.displayName);
        }
        return Optional.empty();
      }

      @Override
      public List<Path<?>> getFields() {
        return Arrays.<Path<?>>asList(MODEL_BACKED_TABLE.id, MODEL_BACKED_TABLE.displayName);
      }

      @Override
      public Path<?> getSelfPath() {
        return MODEL_BACKED_TABLE;
      }

      @Override
      public Optional<DataModel> getDataModel() {
        return Optional.of(primaryKeyModel());
      }
    };
    return new BaseTranspileContext(source, TABLE_NAME);
  }

  private static BaseTranspileContext incompleteMetadataContext() {
    FieldSource source = new FieldSource() {
      @Override
      public Optional<Path<?>> getField(String fieldName) {
        if ("Id".equals(fieldName)) {
          return Optional.of(INCOMPLETE_METADATA_TABLE.id);
        }
        if ("DisplayName".equals(fieldName)) {
          return Optional.of(INCOMPLETE_METADATA_TABLE.displayName);
        }
        return Optional.empty();
      }

      @Override
      public List<Path<?>> getFields() {
        return Arrays.<Path<?>>asList(INCOMPLETE_METADATA_TABLE.id, INCOMPLETE_METADATA_TABLE.displayName);
      }

      @Override
      public Path<?> getSelfPath() {
        return INCOMPLETE_METADATA_TABLE;
      }
    };
    return new BaseTranspileContext(source, TABLE_NAME);
  }

  private static DataModel primaryKeyModel() {
    var id = (DataModelField) Proxy.newProxyInstance(
        SqlDataAdapterGeneratedKeyMetadataTest.class.getClassLoader(),
        new Class<?>[]{DataModelField.class},
        (proxy, method, args) -> "getRawName".equals(method.getName()) ? "Id" : null);
    return (DataModel) Proxy.newProxyInstance(
        SqlDataAdapterGeneratedKeyMetadataTest.class.getClassLoader(),
        new Class<?>[]{DataModel.class},
        (proxy, method, args) -> "getPrimaryKeys".equals(method.getName())
            ? Collections.singletonList(id)
            : null);
  }

  private static final class GeneratedKeyTable extends RelationalPathBase<Object> {
    private static final long serialVersionUID = 1L;
    private final NumberPath<Long> id = createNumber("Id", Long.class);
    private final StringPath displayName = createString("DisplayName");

    private GeneratedKeyTable() {
      super(Object.class, "generatedKeyMetadata", "", TABLE_NAME);
      addMetadata(id, ColumnMetadata.named("Id").withIndex(1).ofType(Types.BIGINT).notNull());
      addMetadata(displayName, ColumnMetadata.named("DisplayName").withIndex(2).ofType(Types.VARCHAR));
      createPrimaryKey(id);
    }
  }

  private static final class ModelBackedTable extends RelationalPathBase<Object> {
    private static final long serialVersionUID = 1L;
    private final NumberPath<Long> id = createNumber("Id", Long.class);
    private final StringPath displayName = createString("DisplayName");

    private ModelBackedTable() {
      super(Object.class, "generatedKeyModelMetadata", "", TABLE_NAME);
      addMetadata(id, ColumnMetadata.named("Id").withIndex(1).ofType(Types.BIGINT).notNull());
      addMetadata(displayName, ColumnMetadata.named("DisplayName").withIndex(2).ofType(Types.VARCHAR));
    }
  }

  private static final class IncompleteMetadataTable extends RelationalPathBase<Object> {
    private static final long serialVersionUID = 1L;
    private final NumberPath<Long> id = createNumber("Id", Long.class);
    private final StringPath displayName = createString("DisplayName");

    private IncompleteMetadataTable() {
      super(Object.class, "generatedKeyIncompleteMetadata", "", TABLE_NAME);
      createPrimaryKey(id);
    }
  }

  private static final class GeneratedKeyColumnTrackingDataSource extends DelegatingDataSource {
    private String[] generatedKeyColumnNames;

    private GeneratedKeyColumnTrackingDataSource(JdbcDataSource targetDataSource) {
      super(targetDataSource);
    }

    @Override
    public Connection getConnection() throws SQLException {
      return track(super.getConnection());
    }

    @Override
    public Connection getConnection(String username, String password) throws SQLException {
      return track(super.getConnection(username, password));
    }

    private Connection track(Connection connection) {
      return Connection.class.cast(Proxy.newProxyInstance(
          Connection.class.getClassLoader(),
          new Class<?>[]{Connection.class},
          (proxy, method, args) -> {
            if ("prepareStatement".equals(method.getName())
                && args != null
                && args.length == 2
                && args[1] instanceof String[] columnNames) {
              generatedKeyColumnNames = columnNames.clone();
            }
            try {
              return method.invoke(connection, args);
            } catch (InvocationTargetException e) {
              throw e.getCause();
            }
          }));
    }

    private String[] getGeneratedKeyColumnNames() {
      return generatedKeyColumnNames;
    }
  }
}
