<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>ouroboros-data</artifactId>
        <groupId>com.ouroboros</groupId>
        <version>2.0.0-rc.1-SNAPSHOT</version>
    </parent>

    <artifactId>ouroboros-data-sql-migration</artifactId>
    <name>Ouroboros Data SQL Migration</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.ouroboros</groupId>
            <artifactId>ouroboros-data-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
